### PR TITLE
Target arraybuffer's buffer should be absolute addressed in ecma_op_typedarray_set_with_typedarray

### LINKED ISSUE #2757: heap-buffer-overflow in ecma_op_typedarray_set_with_typedarray
###### Jerry version:

```
Checked revision: f22eea5c

Build command: ./tools/build.py --clean --debug --compile-flag=-fsanitize=address --compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --compile-flag=-g --strip=off --system-allocator=on --linker-flag=-fuse-ld=gold --error-messages=on --logging=on --profile=es2015-subset
```

###### OS:

```
Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```javascript
var v0 = Function('return this;')( );
var v1 = (new Int8Array(149)).subarray(78);
var $ = $(v1.set(v1));
```

###### Backtrace:

```
=================================================================
==11818==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf5b03934 at pc 0xf79ef7b2 bp 0xffee67f8 sp 0xffee63c8
WRITE of size 71 at 0xf5b03934 thread T0
    #0 0xf79ef7b1 in memmove (/usr/lib32/libasan.so.4+0x7a7b1)
    #1 0x566482e6 in ecma_op_typedarray_set_with_typedarray jerryscript/jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c:773
    #2 0x566484da in ecma_builtin_typedarray_prototype_set jerryscript/jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c:814
    #3 0x566461fb in ecma_builtin_typedarray_prototype_dispatch_routine jerryscript/jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.inc.h:67
    #4 0x56644f67 in ecma_builtin_dispatch_routine jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1016
    #5 0x566451c8 in ecma_builtin_dispatch_call jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1041
    #6 0x566529b6 in ecma_op_function_call jerryscript/jerry-core/ecma/operations/ecma-function-object.c:716
    #7 0x56613697 in opfunc_call jerryscript/jerry-core/vm/vm.c:541
    #8 0x56623b1d in vm_execute jerryscript/jerry-core/vm/vm.c:3491
    #9 0x56624393 in vm_run jerryscript/jerry-core/vm/vm.c:3603
    #10 0x5661292e in vm_run_global jerryscript/jerry-core/vm/vm.c:242
    #11 0x56660fb2 in jerry_run jerryscript/jerry-core/api/jerry.c:546
    #12 0x5665dad4 in main jerryscript/jerry-main/main-unix.c:676
    #13 0xf7793e80 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18e80)
    #14 0x56594c40  (jerryscript/gcc_asan_debug/bin/jerry+0x14c40)

0xf5b03934 is located 7 bytes to the right of 173-byte region [0xf5b03880,0xf5b0392d)
allocated by thread T0 here:
    #0 0xf7a5af34 in malloc (/usr/lib32/libasan.so.4+0xe5f34)
    #1 0x5663b47c in jmem_heap_alloc_block_internal jerryscript/jerry-core/jmem/jmem-heap.c:286
    #2 0x5663b54a in jmem_heap_gc_and_alloc_block jerryscript/jerry-core/jmem/jmem-heap.c:320
    #3 0x5663b61e in jmem_heap_alloc_block jerryscript/jerry-core/jmem/jmem-heap.c:366
    #4 0x566244b9 in ecma_alloc_extended_object jerryscript/jerry-core/ecma/base/ecma-alloc.c:112
    #5 0x566815f2 in ecma_create_object jerryscript/jerry-core/ecma/base/ecma-helpers.c:81
    #6 0x5664c3af in ecma_arraybuffer_new_object jerryscript/jerry-core/ecma/operations/ecma-arraybuffer-object.c:49
    #7 0x5663860b in ecma_typedarray_create_object_with_length jerryscript/jerry-core/ecma/operations/ecma-typedarray-object.c:246
    #8 0x56639bf3 in ecma_op_create_typedarray jerryscript/jerry-core/ecma/operations/ecma-typedarray-object.c:624
    #9 0x56645ca2 in ecma_typedarray_helper_dispatch_construct jerryscript/jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-helpers.c:219
    #10 0x56645944 in ecma_builtin_int8array_dispatch_construct jerryscript/jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-int8array.c:68
    #11 0x5664544e in ecma_builtin_dispatch_construct jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1075
    #12 0x56653806 in ecma_op_function_construct jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1047
    #13 0x56613c0f in opfunc_construct jerryscript/jerry-core/vm/vm.c:625
    #14 0x56623b3d in vm_execute jerryscript/jerry-core/vm/vm.c:3503
    #15 0x56624393 in vm_run jerryscript/jerry-core/vm/vm.c:3603
    #16 0x5661292e in vm_run_global jerryscript/jerry-core/vm/vm.c:242
    #17 0x56660fb2 in jerry_run jerryscript/jerry-core/api/jerry.c:546
    #18 0x5665dad4 in main jerryscript/jerry-main/main-unix.c:676
    #19 0xf7793e80 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18e80)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/lib32/libasan.so.4+0x7a7b1) in memmove
Shadow bytes around the buggy address:
  0x3eb606d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb606e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb606f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb60700: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb60710: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x3eb60720: 00 00 00 00 00 05[fa]fa fa fa fa fa fa fa fd fd
  0x3eb60730: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3eb60740: fd fd fd fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb60750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb60760: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb60770: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==11818==ABORTING
```

When creating a non-ASAN binary with build command:
```
./tools/build.py --clean --debug --compile-flag=-m32 --profile=es2015-subset --system-allocator=on --error-messages=on --logging=on
```

Then we get an invalid free issue with this trace:

```
free(): invalid pointer

Program received signal SIGABRT, Aborted.
0xf7fd5059 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7fd5059 in __kernel_vsyscall ()
#1  0xf7de1832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7de2cc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0xf7e23bd3 in ?? () from /lib/i386-linux-gnu/libc.so.6
#4  0xf7e2a7ed in ?? () from /lib/i386-linux-gnu/libc.so.6
#5  0xf7e2bf0b in ?? () from /lib/i386-linux-gnu/libc.so.6
#6  0x565a6e28 in jmem_heap_free_block (ptr=0x566f5830, size=16) at jerryscript/jerry-core/jmem/jmem-heap.c:490
#7  0x565a7074 in jmem_pools_collect_empty () at jerryscript/jerry-core/jmem/jmem-poolman.c:175
#8  0x565a6c44 in jmem_run_free_unused_memory_callbacks (severity=JMEM_FREE_UNUSED_MEMORY_SEVERITY_LOW)
    at jerryscript/jerry-core/jmem/jmem-allocator.c:270
#9  0x565a6d0d in jmem_heap_gc_and_alloc_block (size=24, ret_null_on_error=false)
    at jerryscript/jerry-core/jmem/jmem-heap.c:317
#10 0x565a6de3 in jmem_heap_alloc_block (size=24) at jerryscript/jerry-core/jmem/jmem-heap.c:366
#11 0x565939f9 in ecma_alloc_extended_object (size=24) at jerryscript/jerry-core/ecma/base/ecma-alloc.c:112
#12 0x565a99f6 in ecma_create_object (prototype_object_p=0x566f5160, ext_object_size=24, type=ECMA_OBJECT_TYPE_GENERAL)
    at jerryscript/jerry-core/ecma/base/ecma-helpers.c:81
#13 0x565b2b97 in ecma_instantiate_builtin (obj_builtin_id=ECMA_BUILTIN_ID_ERROR_PROTOTYPE)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:382
#14 0x565b2ac3 in ecma_instantiate_builtin (obj_builtin_id=ECMA_BUILTIN_ID_TYPE_ERROR_PROTOTYPE)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:357
#15 0x565b290b in ecma_builtin_get (builtin_id=ECMA_BUILTIN_ID_TYPE_ERROR_PROTOTYPE)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:297
#16 0x56597d6f in ecma_new_standard_error (error_type=ECMA_ERROR_TYPE)
    at jerryscript/jerry-core/ecma/operations/ecma-exceptions.c:135
#17 0x56597ee5 in ecma_raise_standard_error (error_type=ECMA_ERROR_TYPE, msg_p=0x0)
    at jerryscript/jerry-core/ecma/operations/ecma-exceptions.c:235
#18 0x56597fbd in ecma_raise_type_error (msg_p=0x0)
    at jerryscript/jerry-core/ecma/operations/ecma-exceptions.c:405
#19 0x5658dbe5 in opfunc_call (frame_ctx_p=0xffffccec) at jerryscript/jerry-core/vm/vm.c:535
#20 0x5659374f in vm_execute (frame_ctx_p=0xffffccec, arg_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:3491
#21 0x56593952 in vm_run (bytecode_header_p=0x566f5560, this_binding_value=1450135939, lex_env_p=0x566f51b0, parse_opts=0, 
    arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3603
#22 0x5658d6b7 in vm_run_global (bytecode_p=0x566f5560) at jerryscript/jerry-core/vm/vm.c:242
#23 0x565bbc11 in jerry_run (func_val=1450137171) at jerryscript/jerry-core/api/jerry.c:546
#24 0x565ba5e8 in main (argc=2, argv=0xffffcf84) at jerryscript/jerry-main/main-unix.c:676
```

Commenting out the first line of the test (the declaration of `v0`) and executing it with the non-ASAN build results in an assertion failure:

```
ICE: Assertion 'object_p->type_flags_refs >= ECMA_OBJECT_REF_ONE' failed at jerryscript/jerry-core/ecma/base/ecma-gc.c(ecma_deref_object):151.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
0xf7fd5059 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7fd5059 in __kernel_vsyscall ()
#1  0xf7de1832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7de2cc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5655c778 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/jerry-port/default/default-fatal.c:71
#4  0x565a0bc4 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x565a0bfe in jerry_assert_fail (assertion=0x565e547c "object_p->type_flags_refs >= ECMA_OBJECT_REF_ONE", 
    file=0x565e53bc "jerryscript/jerry-core/ecma/base/ecma-gc.c", 
    function=0x565cee2c <__func__.4279.lto_priv.128> "ecma_deref_object", line=151)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x565b9108 in ecma_deref_object (object_p=0x566f9790) at jerryscript/jerry-core/ecma/base/ecma-gc.c:151
#7  0x565c5c91 in ecma_free_value (value=1450153875)
    at jerryscript/jerry-core/ecma/base/ecma-helpers-value.c:1049
#8  0x5658e485 in opfunc_call (frame_ctx_p=0xffffccdc) at jerryscript/jerry-core/vm/vm.c:557
#9  0x56593f98 in vm_execute (frame_ctx_p=0xffffccdc, arg_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:3491
#10 0x5659419b in vm_run (bytecode_header_p=0x566f9560, this_binding_value=1450152323, lex_env_p=0x566f91b0, parse_opts=0, 
    arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3603
#11 0x5658dec9 in vm_run_global (bytecode_p=0x566f9560) at jerryscript/jerry-core/vm/vm.c:242
#12 0x565b47aa in jerry_run (func_val=1450153459) at jerryscript/jerry-core/api/jerry.c:546
#13 0x565b3172 in main (argc=3, argv=0xffffcf74) at jerryscript/jerry-main/main-unix.c:676
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [JsProFuzz](https://www.researchgate.net/publication/303482425_Fuzzing_JavaScript_Engine_APIs). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #2757, also adds a short path for the case when the source and the target typedarrays are the same.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: tests/jerry/es2015/regression-test-issue-2757.js [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+// distributed under the License is distributed on an "AS IS" BASIS
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+var v0 = Function ('return this;')( );
+var v1 = (new Int8Array (149)).subarray (78);
+
+try {
+  var $ = $(v1.set (v1));
```
Comment (galpeter) [inline tests/jerry/es2015/regression-test-issue-2757.js]: Is there a need to have this in a try catch block? Can't we just call the set simply?

File: tests/jerry/es2015/regression-test-issue-2757.js [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+  assert (false);
+} catch (e) {
+  assert (e instanceof TypeError);
```
Comment (galpeter) [inline tests/jerry/es2015/regression-test-issue-2757.js]: With this we are testing that the `$(..)` call triggers a TypeError. The test case should be a minimal set of operations related to the modification.

**Comment by rerobika** [comment]
@galpeter I've applied your suggestions!
