### PR TITLE
undefined byteLength should be treated 0 in DataView constructor

### LINKED ISSUE #2854: Assertion '!ecma_number_is_nan (num)' failed in ecma_number_is_infinity
###### Jerry version:

```
Checked revision: a2e78164

Build command: ./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### OS:

```
Linux-4.15.0-48-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```javascript
var buffer = new ArrayBuffer()
new DataView(buffer, 0, undefined)
```

###### Backtrace:

```
ICE: Assertion '!ecma_number_is_nan (num)' failed at jerryscript/jerry-core/ecma/base/ecma-helpers-number.c(ecma_number_is_infinity):339.
Error: ERR_FAILED_INTERNAL_ASSERTION

bt
#0  0xf7fd5059 in __kernel_vsyscall ()
#1  0xf77f8832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77f9cc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x56579719 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:71
#4  0x5661495e in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x5661499f in jerry_assert_fail (assertion=0x566a8e20 "!ecma_number_is_nan (num)", file=0x566a9160 "jerryscript/jerry-core/ecma/base/ecma-helpers-number.c", function=0x5666df00 <__func__.2920.lto_priv.750> "ecma_number_is_infinity", line=339) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x5664f01c in ecma_number_is_infinity (num=nan(0x8000000000001)) at jerryscript/jerry-core/ecma/base/ecma-helpers-number.c:339
#7  0x5662b84e in ecma_op_dataview_create (arguments_list_p=0xffffc984, arguments_list_len=3) at jerryscript/jerry-core/ecma/operations/ecma-dataview-object.c:115
#8  0x565b6575 in ecma_builtin_dataview_dispatch_construct (arguments_list_p=0xffffc984, arguments_list_len=3) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-dataview.c:62
#9  0x5662011e in ecma_builtin_dispatch_construct (obj_p=0xf5f00850, arguments_list_p=0xffffc984, arguments_list_len=3) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1075
#10 0x5662f54e in ecma_op_function_construct (func_obj_p=0xf5f00850, this_arg_value=72, arguments_list_p=0xffffc984, arguments_list_len=3) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1062
#11 0x565e8899 in opfunc_construct (frame_ctx_p=0xffffca00) at jerryscript/jerry-core/vm/vm.c:649
#12 0x565f85df in vm_execute (frame_ctx_p=0xffffca00, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3490
#13 0x565f8ebf in vm_run (bytecode_header_p=0xf5303e40, this_binding_value=4126149459, lex_env_p=0xf5d007b0, parse_opts=0, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3609
#14 0x565e75b8 in vm_run_global (bytecode_p=0xf5303e40) at jerryscript/jerry-core/vm/vm.c:266
#15 0x5663ca82 in jerry_run (func_val=4126148931) at jerryscript/jerry-core/api/jerry.c:550
#16 0x56639584 in main (argc=3, argv=0xffffce34) at jerryscript/jerry-main/main-unix.c:742
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #2854.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/ecma/operations/ecma-dataview-object.c [hunk 1]
```diff
@@ -112,7 +112,11 @@ ecma_op_dataview_create (const ecma_value_t *arguments_list_p, /**< arguments li
 
     int32_t byte_length_int32 = ecma_number_to_int32 (byte_length);
 
-    if (ecma_number_is_infinity (byte_length))
+    if (ecma_number_is_nan (byte_length))
+    {
+      viewByteLength = 0;
```
Comment (LaszloLango) [inline jerry-core/ecma/operations/ecma-dataview-object.c]: What if we only initialize the variable on line 100?
