### PR TITLE
Super parsing options should be set only in direct eval call

### LINKED ISSUE #2846: Assertion 'property_p' failed in ecma_op_is_super_called
###### Jerry version:

```
Checked revision: 1cdb3c6c

Build command: ./tools/build.py --clean --debug --compile-flag=-m32
--profile=es2015-subset --system-allocator=on
--error-messages=on --logging=on
```

###### OS:

```
Linux-4.15.0-48-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```javascript
function f ( ) { } 
var B = class extends f { constructor ( ){ eval ( "eval ('super (1, 2, 3, 4)')" ) ; } } 
    C = class extends B { g ( ) { { ( ) => { } } } } 
    D = class extends C { constructor ( ) { super ( ) 
}

g () { eval () } } 
eval = eval.bind()
new D 
```

###### Backtrace:

```
ICE: Assertion 'property_p' failed at jerryscript/jerry-core/ecma/operations/ecma-function-object.c(ecma_op_is_super_called):587.
Error: ERR_FAILED_INTERNAL_ASSERTION

bt
#0  0xf7fd5059 in __kernel_vsyscall ()
#1  0xf7de9832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7deacc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5655cd0d in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:71
#4  0x565a0525 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x565a055f in jerry_assert_fail (assertion=0x565e755b "property_p", file=0x565e6180 "jerryscript/jerry-core/ecma/operations/ecma-function-object.c", function=0x565d4348 <__func__.5577.lto_priv.572> "ecma_op_is_super_called", line=587) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x565aeb34 in ecma_op_is_super_called (lex_env_p=0x566fc1b0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:587
#7  0x5658e5a3 in vm_loop (frame_ctx_p=0xffffc188) at jerryscript/jerry-core/vm/vm.c:1504
#8  0x56592257 in vm_execute (frame_ctx_p=0xffffc188, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3472
#9  0x565924d1 in vm_run (bytecode_header_p=0x566fd800, this_binding_value=1450164611, lex_env_p=0x566fc1b0, parse_opts=12, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3609
#10 0x5658c42a in vm_run_eval (bytecode_data_p=0x566fd800, parse_opts=12) at jerryscript/jerry-core/vm/vm.c:330
#11 0x565adc55 in ecma_op_eval_chars_buffer (code_p=0x566fd7c8 "super (1, 2, 3, 4)", code_buffer_size=18, parse_opts=12) at jerryscript/jerry-core/ecma/operations/ecma-eval.c:116
#12 0x565adb4e in ecma_op_eval (code_p=0x566fd7c0, parse_opts=0) at jerryscript/jerry-core/ecma/operations/ecma-eval.c:58
#13 0x565796cb in ecma_builtin_global_object_eval (x=1450170305) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-global.c:103
#14 0x5657ac39 in ecma_builtin_global_dispatch_routine (builtin_routine_id=68, this_arg=72, arguments_list_p=0xffffc364, arguments_number=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-global.c:1181
#15 0x565a6018 in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_GLOBAL, builtin_routine_id=68, this_arg_value=72, arguments_list_p=0xffffc364, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1016
#16 0x565a6163 in ecma_builtin_dispatch_call (obj_p=0x566fced0, this_arg_value=72, arguments_list_p=0xffffc5e4, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1041
#17 0x565af075 in ecma_op_function_call (func_obj_p=0x566fced0, this_arg_value=72, arguments_list_p=0xffffc5e4, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:716
#18 0x565af6d6 in ecma_op_function_call (func_obj_p=0x566fced0, this_arg_value=72, arguments_list_p=0xffffc5e4, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:961
#19 0x5658c8b2 in opfunc_call (frame_ctx_p=0xffffc5f8) at jerryscript/jerry-core/vm/vm.c:565
#20 0x56592281 in vm_execute (frame_ctx_p=0xffffc5f8, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3478
#21 0x565924d1 in vm_run (bytecode_header_p=0x566fd790, this_binding_value=1450164611, lex_env_p=0x566fc1b0, parse_opts=12, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3609
#22 0x5658c42a in vm_run_eval (bytecode_data_p=0x566fd790, parse_opts=12) at jerryscript/jerry-core/vm/vm.c:330
#23 0x565adc55 in ecma_op_eval_chars_buffer (code_p=0x566fc988 "eval ('super (1, 2, 3, 4)')", code_buffer_size=27, parse_opts=12) at jerryscript/jerry-core/ecma/operations/ecma-eval.c:116
#24 0x565adb4e in ecma_op_eval (code_p=0x566fc980, parse_opts=0) at jerryscript/jerry-core/ecma/operations/ecma-eval.c:58
#25 0x565796cb in ecma_builtin_global_object_eval (x=1450166657) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-global.c:103
#26 0x5657ac39 in ecma_builtin_global_dispatch_routine (builtin_routine_id=68, this_arg=72, arguments_list_p=0xffffc7d4, arguments_number=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-global.c:1181
#27 0x565a6018 in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_GLOBAL, builtin_routine_id=68, this_arg_value=72, arguments_list_p=0xffffc7d4, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1016
#28 0x565a6163 in ecma_builtin_dispatch_call (obj_p=0x566fced0, this_arg_value=72, arguments_list_p=0xffffca54, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1041
#29 0x565af075 in ecma_op_function_call (func_obj_p=0x566fced0, this_arg_value=72, arguments_list_p=0xffffca54, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:716
#30 0x565af6d6 in ecma_op_function_call (func_obj_p=0x566fced0, this_arg_value=72, arguments_list_p=0xffffca54, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:961
#31 0x5658c8b2 in opfunc_call (frame_ctx_p=0xffffca88) at jerryscript/jerry-core/vm/vm.c:565
#32 0x56592281 in vm_execute (frame_ctx_p=0xffffca88, arg_p=0xffffccc4, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3478
#33 0x565924d1 in vm_run (bytecode_header_p=0x566fc830, this_binding_value=1450168915, lex_env_p=0x566fd2b0, parse_opts=0, arg_list_p=0xffffccc4, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3609
#34 0x565af24f in ecma_op_function_call (func_obj_p=0x566fcfa0, this_arg_value=1450168915, arguments_list_p=0xffffccc4, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:792
#35 0x565afb59 in ecma_op_function_construct (func_obj_p=0x566fcfa0, this_arg_value=1450168915, arguments_list_p=0xffffccc5, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1119
#36 0x5658c675 in vm_super_call (frame_ctx_p=0xffffccd8) at jerryscript/jerry-core/vm/vm.c:479
#37 0x56592291 in vm_execute (frame_ctx_p=0xffffccd8, arg_p=0xffffcf04, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3484
#38 0x565924d1 in vm_run (bytecode_header_p=0x566fcc00, this_binding_value=1450168915, lex_env_p=0x566fd270, parse_opts=0, arg_list_p=0xffffcf04, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3609
#39 0x565af24f in ecma_op_function_call (func_obj_p=0x566fd150, this_arg_value=1450168915, arguments_list_p=0xffffcf04, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:792
#40 0x565afb59 in ecma_op_function_construct (func_obj_p=0x566fd150, this_arg_value=1450168915, arguments_list_p=0xffffcf05, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1119
#41 0x5658ca8e in opfunc_construct (frame_ctx_p=0xffffcf28) at jerryscript/jerry-core/vm/vm.c:649
#42 0x565922a1 in vm_execute (frame_ctx_p=0xffffcf28, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3490
#43 0x565924d1 in vm_run (bytecode_header_p=0x566fcc90, this_binding_value=1450164611, lex_env_p=0x566fc1b0, parse_opts=0, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3609
#44 0x5658c355 in vm_run_global (bytecode_p=0x566fcc90) at jerryscript/jerry-core/vm/vm.c:266
#45 0x565b5e74 in jerry_run (func_val=1450167923) at jerryscript/jerry-core/api/jerry.c:550
#46 0x565b4807 in main (argc=3, argv=0xffffd1d4) at jerryscript/jerry-main/main-unix.c:742
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #2846.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/ecma/builtin-objects/ecma-builtin-global.c [hunk 1]
```diff
@@ -27,6 +27,7 @@
 #include "lit-magic-strings.h"
 #include "lit-strings.h"
 #include "vm.h"
+#include "jcontext.h"
```
Comment (LaszloLango) [inline jerry-core/ecma/builtin-objects/ecma-builtin-global.c]: This include looks unnecessary to me.

Comment (rerobika) [reply jerry-core/ecma/builtin-objects/ecma-builtin-global.c]: It's necessary since the `ECMA_GET_SUPER_EVAL_PARSER_OPTS` macro references to the `JERRY_CONTEXT(status_flags)` field.
