### PR TITLE
Fix the order of value finalizing in ecma_builtin_typedarray_prototype_join

### LINKED ISSUE #2724: Assertion 'ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p)' failed in ecma_free_string_list
###### Jerry version:

```
Checked revision: a42f239a

Build command: ./tools/build.py --clean --debug --compile-flag=-m32 --profile=es2015-subset --system-allocator=on --error-messages=on --logging=on
```

###### OS:

```
Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```javascript
var obj = { reverse : Int32Array.prototype.join } ; 
Object.defineProperty( obj, 'length', { 'get' : function(toPrecision) { return Object.create(/x/); }});
obj.reverse("$01$02$11$20");
```

###### Backtrace:

```
Script Error: TypeError: Incomplete RegExp type
ICE: Assertion 'ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p)' failed at jerryscript/jerry-core/ecma/base/ecma-literal-storage.c(ecma_free_string_list):43.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
0xf7fd5059 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7fd5059 in __kernel_vsyscall ()
#1  0xf7de1832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7de2cc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5655c9ec in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/jerry-port/default/default-fatal.c:71
#4  0x5659fee0 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x5659ff1a in jerry_assert_fail (assertion=0x565e630c "ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p)", 
    file=0x565e62c0 "jerryscript/jerry-core/ecma/base/ecma-literal-storage.c", 
    function=0x565cea88 <__func__.3807.lto_priv.89> "ecma_free_string_list", line=43)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x565c9bf0 in ecma_free_string_list (string_list_p=0x566f77f0)
    at jerryscript/jerry-core/ecma/base/ecma-literal-storage.c:43
#7  0x565c9c8c in ecma_finalize_lit_storage () at jerryscript/jerry-core/ecma/base/ecma-literal-storage.c:63
#8  0x565c9428 in ecma_finalize () at jerryscript/jerry-core/ecma/base/ecma-init-finalize.c:63
#9  0x565b4659 in jerry_cleanup () at jerryscript/jerry-core/api/jerry.c:210
#10 0x565b3b0c in main (argc=3, argv=0xffffcf74) at jerryscript/jerry-main/main-unix.c:874
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #2724.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c [hunk 1]
```diff
@@ -1052,9 +1052,9 @@ ecma_builtin_typedarray_prototype_join (ecma_value_t this_arg, /**< this argumen
   }
   ecma_free_value (separator_value);
 
+  ECMA_OP_TO_NUMBER_FINALIZE (length_number);
```
Comment (LaszloLango) [inline jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c]: Something is messed up here. There should be no `return` statements between `ECMA_OP_TO_NUMBER_TRY_CATCH` and `ECMA_OP_TO_NUMBER_FINALIZE`. IMHO this function needs a serious refactoring.

Comment (rerobika) [reply jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c]: Probably it's not the best practice to return between these macros, but in this case all early return statements contains the required `ecma_free_values` which generally present at the and of the function. I'd also vote for a refactor, but it may worth an other PR, since this PR's aim to fix the reported issue only.
